Repository hiero-ledger/hiero-sdk-go, pull requests merged in 2024-11, with the labels that each got.

#1128 feat: Replace go-ethereum RLP lib
  ethereum_data_unit_test.go
  ethereum_eip1559_transaction.go
  ethereum_legacy_transaction.go
  ethereum_transaction_data.go
  ethereum_transaction_e2e_test.go
  examples/rlp/main.go
  rlp.go
  rlp_unit_test.go
Labels: enhancement

#1135 fix: Retry in case of throttle when calling `getRecord`
  transaction_response.go
Labels: bug

#1143 chore: Updated tck/README.md
  README.md
  go.mod
  tck/README.md
  tck/go.mod
  tck/go.sum
Labels: documentation

#1148 chore: Updated the runners to associate with hiero-client-sdk
  .github/workflows/build.yml
  .github/workflows/main.yml
  .github/workflows/previewnet.yml
  .github/workflows/testnet.yml
Labels: github_actions

#1153 fix: max backoff
  account_balance_query_e2e_test.go
  executable.go
  go.mod
  go.sum
  tck/go.mod
  tck/go.sum
Labels: bug
